stages:
  - pull
  - install
  - build

variables:
  IMAGE_NAME: isi_burger
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Étape 1 : Pull du code
pull_code:
  stage: pull
  script:
    - echo " Code récupéré depuis la branche diallo_fatoumata_diarra_burger"
    - git log -1 --oneline
  only:
    - diallo_fatoumata_diarra_burger

# Étape 2 : Installation des dépendances Laravel
install_dependencies:
  stage: install
  image: php:8.3-cli
  before_script:
    - apt-get update && apt-get install -y git curl zip unzip libpng-dev libonig-dev libxml2-dev
    - docker-php-ext-install pdo_mysql mbstring
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --optimize-autoloader --no-dev
    - cp .env.example .env
    - php artisan key:generate
    - echo " Dépendances installées avec succès"
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 hour
  only:
    - diallo_fatoumata_diarra_burger

# Étape 3 : Build de l'image Docker
build_docker:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - docker info
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker images | grep $IMAGE_NAME
    - echo "Image Docker $IMAGE_NAME:latest construite avec succès"
  only:
    - diallo_fatoumata_diarra_burger
